-- 코드를 입력하세요
SELECT B.CATEGORY, SUM(BS.SALES) AS TOTAL_SALES
FROM BOOK_SALES AS BS
LEFT OUTER JOIN BOOK AS B ON B.BOOK_ID = BS.BOOK_ID
WHERE BS.SALES_DATE >= '2022-01-01' AND BS.SALES_DATE <= '2022-01-31'
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY ASC;